### ISSUE TITLE
SPF crashes on code with exception handlers for calling a method of `null`

### ISSUE THREAD

**Issue by maemre** [SymbolicPathFinder/jpf-symbc#27]
The following code causes SPF to crash (because it tries to get arguments to function call while the caller frame is unrolled? I'm not sure):

```
class A {
    void foo() {}
}

public class Driver {
    public static void main(String[] args) {
        try {
            ((A)null).foo();
        } catch (NullPointerException ex) {
        }
    }
}
```

Here is the JPF configuration used:

```
target=Driver
classpath=.
symbolic.method=Driver.main(con)
search.depth_limit=1
listener+=,gov.nasa.jpf.symbc.SymbolicListener
vm.storage.class=nil
search.multiple_errors=true
symbolic.dp=no_solver
symbolic.strings=false
symbolic.lazy=off
symbolic.debug=true
```

Note that the values of `search.depth_limit`, `vm.storage.class`, `search.multiple_errors`,  `symbolic.lazy`, `symbolic.debug`, `symbolic.strings`, `symbolic.dp` do not affect the crash. 

Here is the JPF output with the error:

```
Running Symbolic PathFinder ...
symbolic.dp=no_solver
symbolic.string_dp_timeout_ms=0
symbolic.string_dp=none
symbolic.max_pc_length=2147483647
symbolic.max_pc_msec=0
symbolic.bvlength=32
symbolic.min_int=-2147483648
symbolic.min_long=-9223372036854775808
symbolic.min_short=-32768
symbolic.min_byte=-128
symbolic.min_char=0
symbolic.max_int=2147483647
symbolic.max_long=9223372036854775807
symbolic.max_short=32767
symbolic.max_byte=127
symbolic.max_char=65535
symbolic.min_double=4.9E-324
symbolic.max_double=1.7976931348623157E308
JavaPathfinder core system v8.0 (rev d275f72b1878404b0b4d80a4845969d3370f0e06) - (C) 2005-2014 United States Government. All rights reserved.


====================================================== system under test
Driver.main()

====================================================== search started: 1/25/19 3:41 PM
[SEVERE] JPF exception, terminating: exception during instructionExecuted() notification
java.lang.AssertionError: can't find caller stackframe for: invokevirtual A.foo()V
	at gov.nasa.jpf.jvm.bytecode.JVMInvokeInstruction.getArgumentValues(JVMInvokeInstruction.java:167)
	at gov.nasa.jpf.symbc.SymbolicListener.instructionExecuted(SymbolicListener.java:181)
	at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:808)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1922)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during instructionExecuted() notification
	at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:815)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1922)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:579)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:613)
	at gov.nasa.jpf.JPF.start(JPF.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
Caused by: java.lang.AssertionError: can't find caller stackframe for: invokevirtual A.foo()V
	at gov.nasa.jpf.jvm.bytecode.JVMInvokeInstruction.getArgumentValues(JVMInvokeInstruction.java:167)
	at gov.nasa.jpf.symbc.SymbolicListener.instructionExecuted(SymbolicListener.java:181)
	at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:808)
	... 14 more
```

I am using both JPF and SPF compiled from their master branches on GitHub. The input program is compiled using `javac -g`. I am using 64-bit Java 1.8.0_181 on Ubuntu 18.04.

**Comment by corinus** [comment]
thanks. i will look.
