### ISSUE TITLE
Math.tan not supported

### ISSUE THREAD

**Issue by dah-fari7009** [SymbolicPathFinder/jpf-symbc#41]
Good evening,
I am trying to run jpf-symbc on a small example containing math functions but I get an exception: 
java.lang.RuntimeException: ## Error: Math.tan not supported
        at gov.nasa.jpf.symbc.numeric.solvers.ProblemGeneral.tan(ProblemGeneral.java:158)
        at gov.nasa.jpf.symbc.numeric.PCParser.getExpression(PCParser.java:327)
        at gov.nasa.jpf.symbc.numeric.PCParser.createDPRealConstraint(PCParser.java:431)
        at gov.nasa.jpf.symbc.numeric.PCParser.addConstraint(PCParser.java:1105)
        at gov.nasa.jpf.symbc.numeric.PCParser.parse(PCParser.java:1091)
        at gov.nasa.jpf.symbc.numeric.SymbolicConstraintsGeneral.isSatisfiable(SymbolicConstraintsGeneral.java:128)

The specified line contains : 

 `double rA = Math.pow(vA, 2.0) / Math.tan(bank_ang*degToRad) / g;`

This is odd, since I did operations with Math.tan before and it was definitely supported.

**Comment by corinus** [comment]
what solver are you using?

**Comment by dah-fari7009** [comment]
I am using z3

**Comment by corinus** [comment]
z3 does not support complex math constraints. you can try using coral.

**Comment by dah-fari7009** [comment]
I understand, thank you. I tried with a simplified example with just
`return Math.tan(x)`

And the error I obtain is totally different : 
[SEVERE] JPF exception, terminating: exception during instructionExecuted() notification
java.lang.RuntimeException: ## Error: PC not solved!
        at gov.nasa.jpf.symbc.numeric.SymbolicReal.solution(SymbolicReal.java:137)
        at gov.nasa.jpf.symbc.numeric.MathRealExpression.solution(MathRealExpression.java:115)
        at gov.nasa.jpf.symbc.SymbolicListener.handleReturnType(SymbolicListener.java:380)
        at gov.nasa.jpf.symbc.SymbolicListener.instructionExecuted(SymbolicListener.java:338)
        at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:808)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1922)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
        at gov.nasa.jpf.search.Search.forward(Search.java:579)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at gov.nasa.jpf.tool.Run.call(Run.java:80)

**Comment by dah-fari7009** [comment]
And I get the same error with coral as well

**Comment by corinus** [comment]
can you please show the full code of the example and the configuration file.

**Comment by dah-fari7009** [comment]
Yes, of course  
Here is my code
`package demo.instrumented;

public class Itest2 {
    double test(double x){
        if(x>0) {
            return Math.tan(x);
        }
        return 6;
    }
public static void main(String[] args){
Itest2 temp = new Itest2();
temp.test(0);
}
}`

**Comment by dah-fari7009** [comment]
Yes of course, 
Here is my code
![Capture](https://user-images.githubusercontent.com/35702512/73484266-d7cc6800-4355-11ea-8124-6779ade6fe15.PNG)

**Comment by dah-fari7009** [comment]
And here is my configuration file
target = demo.instrumented.Itest2
symbolic.method = demo.instrumented.Itest2.test(sym)
classpath=target/classes 
symbolic.min_int=-100 
symbolic.max_int=100 
symbolic.min_long=-100 
symbolic.max_long=100 
symbolic.min_double=1.0 
symbolic.max_double=10.0 
symbolic.debug = true 
symbolic.dp=z3
search.depth_limit=5 
listener = gov.nasa.jpf.symbc.SymbolicListener 
search.multiple_errors=true

**Comment by corinus** [comment]
I am sorry I am not able to reproduce the error. May I ask what java version are you using?
Also in the config file please add 

symbolic.debug=true

this may help you with debugging

**Comment by dah-fari7009** [comment]
I am using Java 8

**Comment by dah-fari7009** [comment]
I get the exact same error if I switch to cos or sin

**Comment by dah-fari7009** [comment]
Oh, I just realized that the error might I have to do with some custom classes I added to handle uninterpreted functions. Sorry about this :(

**Comment by dah-fari7009** [comment]
I tried with the original settings and now I obtain no path conditions while there is clearly a branching

numeric PC: constraint # = 1
5: x_1_SYMREAL < CONST_0.0 -> false

### PCs: total:1 sat:0 unsat:1

numeric PC: constraint # = 1
5: CONST_0.0 = x_1_SYMREAL -> false

### PCs: total:2 sat:0 unsat:2

numeric PC: constraint # = 1
5: x_1_SYMREAL > CONST_0.0 -> true

### PCs: total:3 sat:1 unsat:2

string analysis: SPC # = 0
NPC constraint # = 1
5: x_1_SYMREAL > CONST_0.0

====================================================== Method Summaries
Inputs: x_1_SYMREAL
No path conditions for demo.instrumented.Itest1.test(1.0)

**Comment by corinus** [comment]
There are path conditions; see all the PCs displays :) seems the listener is broken. I will look into fixing it. For now please use the debug feature.

**Comment by dah-fari7009** [comment]
I understand, thank you . By using the debug feature, do you mean adding symbolic.debug = true ?

**Comment by corinus** [comment]
yes

**Comment by dah-fari7009** [comment]
Noted. Thank you for your help

**Comment by corinus** [comment]
to use the listener you may need to add the following option:

symbolic.optimizechoices=false

I am yet to look into it more carefully -- Corina

**Comment by dah-fari7009** [comment]
I will do that. Thank you  )
