### ISSUE TITLE
java.lang.ClassCastException: gov.nasa.jpf.symbc.arrays.ArrayConstraint cannot be cast to gov.nasa.jpf.symbc.numeric.NonLinearIntegerConstraint

### ISSUE THREAD

**Issue by woshazi** [SymbolicPathFinder/jpf-symbc#6]
I am trying to learn how array works with SPF by using the provided array examples and jpf's (e.g., in examples/arrays),  but for each of these examples I get the error 

java.lang.ClassCastException: gov.nasa.jpf.symbc.arrays.ArrayConstraint cannot be cast to gov.nasa.jpf.symbc.numeric.NonLinearIntegerConstraint
	at gov.nasa.jpf.symbc.numeric.PCParser.addConstraint(PCParser.java:960)
	at gov.nasa.jpf.symbc.numeric.PCParser.parse(PCParser.java:929)
	atgov.nasa.jpf.symbc.numeric.SymbolicConstraintsGeneral.isSatisfiable(SymbolicConstraintsGeneral.java:142)
	at gov.nasa.jpf.symbc.numeric.PathCondition.simplifyOld(PathCondition.java:459)
	at gov.nasa.jpf.symbc.numeric.PathCondition.simplify(PathCondition.java:336)
	at gov.nasa.jpf.symbc.bytecode.symarrays.IASTORE.execute(IASTORE.java:156)
	at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1909)
	at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1859)
	at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
	at gov.nasa.jpf.vm.VM.forward(VM.java:1722)
	at gov.nasa.jpf.search.Search.forward(Search.java:580)
	at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
	at gov.nasa.jpf.JPF.run(JPF.java:633)
	at gov.nasa.jpf.JPF.start(JPF.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at gov.nasa.jpf.tool.Run.call(Run.java:80)
	at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)

**Comment by R1kM** [comment]
Hi,

Did you clone the current version of the code from Github? When looking at PCParser mentioned in the error trace, l. 929 corresponds to an empty line, and l.960 only contains a single bracket.

This error occurred previously due to a partial merge, but it should have been corrected in the current version

**Comment by woshazi** [comment]
Thank you ,it works.
